### ISSUE TITLE
WDI-BOS-04: Post fixed N+1 issues here

### ISSUE THREAD

**Issue by digitalcora** [ga-wdi-boston/wdi_10_rails_query_optimization#1]
Reply to this issue with direct links to at least **three** separate commits where you resolved an N+1 issue using eager loading or counter caching.

**Comment by csb324** [comment]
https://github.com/csb324/HangAtBrown/commit/98b527cc2cfdaf2b36c244c7a6b957f0e201c79e
https://github.com/csb324/HangAtBrown/commit/b88b2661d12008067dd5e7f340e7a6611a732356
https://github.com/csb324/HangAtBrown/commit/eec0c8dc4228c5d0d2b43242ba18f1b1a55341bd

**Comment by devindreszer** [comment]
Three in 1
https://github.com/devindreszer/rescue_dogs/commit/58bb09b25d73545a4041c3a1d6822ff3f428b231

**Comment by emmagard** [comment]
https://github.com/emmagard/at_a_glance/commit/684685840f2ffca8d1d5329c25eb5ccfbace170d#diff-d41d8cd98f00b204e9800998ecf8427e

https://github.com/zhbanton/photo_mixer/commit/af5ead10fb8e503a1381141de696ebfe8ad943cd#diff-d41d8cd98f00b204e9800998ecf8427e

https://github.com/zhbanton/photo_mixer/commit/a7bc0e634fac91129f502a29cf51620b9989f579#diff-d41d8cd98f00b204e9800998ecf8427e

**Comment by dmcgann1** [comment]
https://github.com/dmcgann1/Sportfinder/commit/9758acec7102ef3b32685a8f37f4210f58f421e1

**Comment by brian-penguin** [comment]
https://github.com/csb324/getdated/commit/9db37b81755579ac64b9231f4015b17f9619fb8f
https://github.com/csb324/getdated/commit/c313c284cb7f5085ea5c6c7afd2992657e972444
https://github.com/csb324/getdated/commit/3959c79ffc35564f37e71f06559dc17682916145

**Comment by maxkohl88** [comment]
https://github.com/maxkohl88/fantasy_history_2.0/commit/196dd2cc8ccc5d4e4204a31bacc43844153e37ce

**Comment by zhbanton** [comment]
1. https://github.com/zhbanton/conehead/commit/25622c057f00652e8bedbbb631bc9f3d163b83ed
2. https://github.com/zhbanton/conehead/commit/5d833a931bf3b46e1c8f9a42627624137252080d
3. https://github.com/zhbanton/conehead/commit/58ed728e380cf2df08c63375970c7275ca08b070

**Comment by krk324** [comment]
https://github.com/krk324/supworld/commit/b3b9fb4b17d69d7946195831206bc634287eedaa
https://github.com/krk324/supworld/commit/5e92bef81d19629838991886af21f96b2a0ac1b6

**Comment by jakeaustin** [comment]
Three in one
https://github.com/jakeaustin/potlucky/commit/fa440b348335193cdd890944ca5ecbaeeb6700af

**Comment by afeinber** [comment]
https://github.com/afeinber/mybooks/commit/2237315ab21205e8d7a9426ff6d60aa5546396dd
https://github.com/afeinber/mybooks/commit/454ff95054201e0a2438e068d736ede664465376
